USE [master]
GO

/****** Object:  Database [transirestoredb]    Script Date: 30/06/2018 09:29:41 ******/
CREATE DATABASE [transirestoredb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'transirestoredb', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\transirestoredb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'transirestoredb_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\transirestoredb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [transirestoredb] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [transirestoredb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [transirestoredb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [transirestoredb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [transirestoredb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [transirestoredb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [transirestoredb] SET ARITHABORT OFF 
GO

ALTER DATABASE [transirestoredb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [transirestoredb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [transirestoredb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [transirestoredb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [transirestoredb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [transirestoredb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [transirestoredb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [transirestoredb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [transirestoredb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [transirestoredb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [transirestoredb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [transirestoredb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [transirestoredb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [transirestoredb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [transirestoredb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [transirestoredb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [transirestoredb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [transirestoredb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [transirestoredb] SET  MULTI_USER 
GO

ALTER DATABASE [transirestoredb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [transirestoredb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [transirestoredb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [transirestoredb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [transirestoredb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [transirestoredb] SET QUERY_STORE = OFF
GO

USE [transirestoredb]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [transirestoredb] SET  READ_WRITE 
GO

